# https://taskfile.dev

version: '3'

tasks:

  install:
    desc: Install dependencies
    cmds:
      - uv sync --locked --all-extras --dev
      - uv pip install -e .

  lint:
    desc: Lint the codebase
    cmds:
      - uv run ruff check {{ .CLI_ARGS }}

  format:
    desc: Format the codebase
    cmds:
      - uv run ruff format {{ .CLI_ARGS }}

  test:unit:
    desc: Run tests
    cmds:
      - uv run pytest tests -v

  test:
    desc: Run all tests
    cmds:
      - task: format
      - task: lint
      - task: test:unit
