# https://taskfile.dev

version: '3'

tasks:

  install:
    desc: Install dependencies
    cmds:
      - uv sync --locked --all-extras --all-packages --dev

  lint:
    desc: Lint the codebase
    cmds:
      - uv run pyrefly check
      - uv run ruff check

  format:
    desc: Format the codebase
    cmds:
      - uv run pyrefly infer
      - uv run ruff check --fix
      - uv run ruff format

  test:unit:
    desc: Run tests with coverage
    cmds:
      - uv run pytest tests

  test:watch:
    desc: Run tests in watch mode
    silent: true
    watch: true
    sources:
      - tests/**/*.py
      - ghanon/**/*.py
    cmds:
      - uv run pytest tests -qq --no-cov

  test:update:
    desc: Update test snapshots
    cmds:
      - rm -rf __snapshots__
      - task: test:unit

  test:
    desc: Run all tests
    cmds:
      - task: format
      - task: lint
      - task: test:unit

  run:
    desc: Run the application
    silent: true
    cmds:
      - uv run python main.py {{ .CLI_ARGS }}
